// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpRPVbuzrh3IjbsDg8JD5RidOCrs5qcs',
    appId: '1:405536348219:web:b0d0d374ba338cb498e41e',
    messagingSenderId: '405536348219',
    projectId: 'fbpro9ea',
    authDomain: 'fbpro9ea.firebaseapp.com',
    storageBucket: 'fbpro9ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLeYssslOrU1hEUV4JliaDoeyVwptzW9k',
    appId: '1:405536348219:android:b7c94e6543724bd198e41e',
    messagingSenderId: '405536348219',
    projectId: 'fbpro9ea',
    storageBucket: 'fbpro9ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeudy5C5vPe7Yc8oU_hcUW68irJcJXZto',
    appId: '1:405536348219:ios:fed4003474046b9b98e41e',
    messagingSenderId: '405536348219',
    projectId: 'fbpro9ea',
    storageBucket: 'fbpro9ea.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeudy5C5vPe7Yc8oU_hcUW68irJcJXZto',
    appId: '1:405536348219:ios:0d101ff986471acb98e41e',
    messagingSenderId: '405536348219',
    projectId: 'fbpro9ea',
    storageBucket: 'fbpro9ea.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
